# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efea892fecbc8247a228a9d8b3b7aa228faf5252562e9ae1711b5cc26dcd27447ac5adf50efb877cef6010b03462a3c8fbf4a613cd7724cf3028e069d19609e4

test:
  secret_key_base: 5fa8621ba074e7b0697cb120953265a8c75e0cdade0c14beac914b43eb0c6b44367f97c41d654c5954ef7f30c0932fb6b81638d5b872a26565d0b7923b19e140

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
